=== Demokratis-ch/demokratis-ml/src/evaluation/json_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "DocNode",
    "type": "object",
    "properties": {
      "label": {
        "type": "string",
        "description": "Label of the node, e.g. '1.2' or '1bis' or 'a)' etc. May be empty."
      },
      "type": {
        "type": "string",
        "enum": ["document", "heading", "content", "list", "list_item", "footnote", "image", "table"],
        "description": "Type of the node."
      },
      "content": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "Array of content strings. Usually only one string, but may be more in case of multiple paragraphs."
      },
      "children": {
        "type": "array",
        "items": {
          "$ref": "#"
        },
        "description": "Array of nested nodes."
      },
      "indent_level": {
        "type": "integer",
        "description": "Indentation level of the node. 0 is the leftmost."
      }
    },
    "required": ["label", "type"],
    "additionalProperties": false
  }

=== Demokratis-ch/demokratis-ml/research/mlartifacts/359746332828124238/6c0069a1bf3e4b8d9ed24d094d765831/artifacts/51276-de-DRAFT-92be4e18116eab4615da2a4279771eb05b4f47e2_parsed.json
{
    "label": "",
    "type": "document",
    "content": [],
    "children": [
        {
            "label": "",
            "type": "section",
            "content": [
                "Vorentwurf der KVF-S 22.407 / 22.417 f\u00fcr die Vernehmlassung"
            ],
            "children": [
                {
                    "label": "I",
                    "type": "heading",
                    "content": [
                        "Das Bundesgesetz vom 24. M\u00e4rz 2006 \u00fcber Radio und Fernsehen"
                    ],
                    "children": [
                        {
                            "label": "",
                            "type": "content",
                            "content": [
                                "Das Bundesgesetz \u00fcber Radio und Fernsehen wird wie folgt ge\u00e4ndert:"
                            ],
                            "children": []
                        },
                        {
                            "label": "Art. 1",
                            "type": "heading",
                            "content": [
                                "Sach\u00fcberschrift, Abs. 1 und 1bis \u2013 Gegenstand und Geltungsbereich"
                            ],
                            "children": [
                                {
                                    "label": "1.",
                                    "type": "paragraph",
                                    "content": [
                                        "Dieses Gesetz regelt die Veranstaltung, die Aufbereitung, die \u00dcbertragung und den Empfang von Radio- und Fernsehprogrammen, sowie die F\u00f6rdermassnahmen zugunsten der elektronischen Medien."
                                    ],
                                    "children": []
                                },
                                {
                                    "label": "1bis.",
                                    "type": "paragraph",
                                    "content": [
                                        "Soweit in diesem Gesetz nichts anderes vorgesehen ist, richtet sich die fernmeldetechnische \u00dcbertragung von Programmen nach dem Fernmeldegesetz vom 30. April 1997 (FMG)."
                                    ],
                                    "children": []
                                }
                            ]
                        },
                        {
                            "label": "Art. 2",
                            "type": "heading",
                            "content": [
                                "Bst. abis \u2013 Definition"
                            ],
                            "children": [
                                {
                                    "label": "ab.",
                                    "type": "paragraph",
                                    "content": [
                                        "In diesem Gesetz bedeuten elektronische Medien Angebote, die fernmeldetechnisch \u00fcbertragen werden, f\u00fcr die Allgemeinheit bestimmt sind und nach redaktionellen Kriterien zusammengestellt werden."
                                    ],
                                    "children": []
                                }
                            ]
                        },
                        {
                            "label": "Art. 38",
                            "type": "heading",
                            "content": [
                                "Abs. 3"
                            ],
                            "children": [
                                {
                                    "label": "3.",
                                    "type": "paragraph",
                                    "content": [
                                        "Lokalen TV-Stationen mit einer eigenst\u00e4ndigen und regelm\u00e4ssigen Berichterstattung \u00fcber nationale und kantonale Politik kann eine zus\u00e4tzliche Konzession mit Abgabenanteil erteilt werden."
                                    ],
                                    "children": []
                                }
                            ]
                        },
                        {
                            "label": "Art. 40",
                            "type": "heading",
                            "content": [
                                "Abs. 1 und 2"
                            ],
                            "children": [
                                {
                                    "label": "1.",
                                    "type": "paragraph",
                                    "content": [
                                        "Die Abgabenanteile f\u00fcr Veranstalter betragen 6 bis 8 Prozent des Ertrages der Abgabe f\u00fcr Radio und Fernsehen."
                                    ],
                                    "children": []
                                }
                            ]
                        }
                    ]
                },
                {
                    "label": "II",
                    "type": "heading",
                    "content": [
                        "Bestimmungen zum Inkrafttreten"
                    ],
                    "children": [
                        {
                            "label": "1.",
                            "type": "paragraph",
                            "content": [
                                "Dieses Gesetz untersteht dem fakultativen Referendum."
                            ],
                            "children": []
                        },
                        {
                            "label": "2.",
                            "type": "paragraph",
                            "content": [
                                "Der Bundesrat bestimmt das Inkrafttreten."
                            ],
                            "children": []
                        }
                    ]
                }
            ]
        }
    ]
}

=== Demokratis-ch/demokratis-ml/research/mlartifacts/359746332828124238/3e9894e10c644e8a990c325a3be9d2c6/artifacts/jpxdh228 - zh - Entwurf-1_(EnerG-Aenderung-Staerkung-Versorgungssicherheit_Vernehmlassung)_parsed.json
{
    "label": "",
    "type": "document",
    "content": [],
    "children": [
        {
            "label": "",
            "type": "heading",
            "content": [
                "\u00c4nderung Energiegesetz, St\u00e4rkung der Versorgungssicherheit durch Solard\u00e4cher und Saisonspeicher"
            ],
            "children": []
        },
        {
            "label": "",
            "type": "heading",
            "content": [
                "Vernehmlassung"
            ],
            "children": []
        },
        {
            "label": "",
            "type": "heading",
            "content": [
                "Zusammenfassung"
            ],
            "children": [
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Der Umstieg von fossilen Heizungen auf W\u00e4rmepumpen sowie der Umstieg auf Elektromobilit\u00e4t wird in den n\u00e4chsten Jahrzehnten zu einem Anstieg des Stromverbrauchs f\u00fchren. Mittelfristig wird zudem die Stromerzeugung aus der Kernkraft in der Schweiz schrittweise zur\u00fcckgehen. Es ist jedoch nicht sicher, dass die Schweiz jederzeit gen\u00fcgend Strom aus dem Ausland importieren kann."
                    ],
                    "children": []
                }
            ]
        },
        {
            "label": "I",
            "type": "heading",
            "content": [
                "Besondere Massnahmen"
            ],
            "children": [
                {
                    "label": "1",
                    "type": "heading",
                    "content": [
                        "Energiesparmassnahmen und Nutzung erneuerbarer Energien"
                    ],
                    "children": []
                },
                {
                    "label": "a)",
                    "type": "list",
                    "content": [],
                    "children": [
                        {
                            "label": "1)",
                            "type": "list_item",
                            "content": [
                                "Auf grossen, geeigneten D\u00e4chern ist fl\u00e4chendeckend eine Solaranlage zu installieren, wenn dies technisch m\u00f6glich und wirtschaftlich ist und nicht \u00fcberwiegende \u00f6ffentliche Interessen entgegenstehen:"
                            ],
                            "children": []
                        }
                    ]
                },
                {
                    "label": "b)",
                    "type": "list",
                    "content": [],
                    "children": [
                        {
                            "label": "1.",
                            "type": "list_item",
                            "content": [
                                "bei Neubauten,"
                            ],
                            "children": []
                        },
                        {
                            "label": "2.",
                            "type": "list_item",
                            "content": [
                                "bei der umfassenden Sanierung des Dachs oder sp\u00e4testens bis 2040."
                            ],
                            "children": []
                        }
                    ]
                },
                {
                    "label": "2",
                    "type": "heading",
                    "content": [
                        "Wirtschaftlichkeitsnachweis"
                    ],
                    "children": [
                        {
                            "label": "",
                            "type": "content",
                            "content": [
                                "Von den Anforderungen ausgenommen ist, wer nachweist, dass bei Ber\u00fccksichtigung der Investitionskosten und der Betriebskosten sowie des Ertrags \u00fcber die Lebensdauer die Anlage nicht wirtschaftlich ist."
                            ],
                            "children": []
                        }
                    ]
                }
            ]
        },
        {
            "label": "II",
            "type": "heading",
            "content": [
                "F\u00f6rderung der Energiespeicherung durch die Stromnetzbetreiber"
            ],
            "children": [
                {
                    "label": "1",
                    "type": "heading",
                    "content": [
                        "F\u00f6rderung der saisonalen Speicherung"
                    ],
                    "children": [
                        {
                            "label": "",
                            "type": "content",
                            "content": [
                                "Zur St\u00e4rkung der Stromversorgungssicherheit im Winterhalbjahr f\u00f6rdern die Netzbetreiber die saisonale Speicherung von Energie."
                            ],
                            "children": []
                        },
                        {
                            "label": "a)",
                            "type": "list",
                            "content": [],
                            "children": [
                                {
                                    "label": "1.",
                                    "type": "list_item",
                                    "content": [
                                        "wettbewerbliche Ausschreibungen,"
                                    ],
                                    "children": []
                                },
                                {
                                    "label": "2.",
                                    "type": "list_item",
                                    "content": [
                                        "Unterst\u00fctzung von Projekten und Anlagen, die der Erprobung, Anwendung und Bekanntmachung von neuartigen Technologien und Prozessen dienen."
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "label": "III",
            "type": "heading",
            "content": [
                "Schlussbestimmungen"
            ],
            "children": [
                {
                    "label": "1",
                    "type": "heading",
                    "content": [
                        "Vollzug"
                    ],
                    "children": [
                        {
                            "label": "",
                            "type": "content",
                            "content": [
                                "Der Regierungsrat regelt durch Verordnung:"
                            ],
                            "children": []
                        },
                        {
                            "label": "a)",
                            "type": "list",
                            "content": [],
                            "children": [
                                {
                                    "label": "1.",
                                    "type": "list_item",
                                    "content": [
                                        "die Durchf\u00fchrung der kantonalen Energieplanung,"
                                    ],
                                    "children": []
                                },
                                {
                                    "label": "2.",
                                    "type": "list_item",
                                    "content": [
                                        "die Rechte und Pflichten der Beteiligten bei der Mitwirkung an der Energieplanung."
                                    ],
                                    "children": []
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

=== Demokratis-ch/demokratis-ml/research/structure-extraction/sample-outputs/ch/consultation_4956_2024-11-21/53136-fr-DRAFT-8ebcf00d65424618bcfd8b2b792bfacdc7514935_json_schema.json
{
    "label": "",
    "type": "document",
    "content": [],
    "children": [
        {
            "label": "1",
            "type": "heading",
            "content": [
                "Loi f\u00e9d\u00e9rale sur les \u00e9trangers et l'int\u00e9gration (LEI)"
            ],
            "children": [
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "*Avant-projet*"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "(Pas de perte du droit de s\u00e9jour en cas de d\u00e9pendance non fautive de l'aide sociale)"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Modification du ..."
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "L'Assembl\u00e9e f\u00e9d\u00e9rale de la Conf\u00e9d\u00e9ration suisse,"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "vu le rapport de la [nom de la commission du Conseil national/des Etats] du [date d\u00e9cision de la commission][^FF 2002 ...],"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "vu l'avis du Conseil f\u00e9d\u00e9ral du [date][^FF 2002 ...],"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "arr\u00eate:"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "I"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "La loi f\u00e9d\u00e9rale du 16 d\u00e9cembre 2005[^SR 142.20] sur les \u00e9trangers et l'int\u00e9gration est modifi\u00e9e comme suit:"
                    ]
                }
            ]
        },
        {
            "label": "2",
            "type": "heading",
            "content": [
                "Art. 62, al. 1bis"
            ],
            "children": [
                {
                    "label": "",
                    "type": "list",
                    "children": [
                        {
                            "label": "1bis.",
                            "type": "list_item",
                            "content": [
                                "Lors de l'examen d'une \u00e9ventuelle r\u00e9vocation selon l'al. 1, let. e, il convient d'examiner si la personne a par sa propre faute provoqu\u00e9 sa d\u00e9pendance \u00e0 l'aide sociale et si elle a insuffisamment exploit\u00e9 son potentiel de travail ou les autres possibilit\u00e9s qu'elle avait de s'affranchir durablement de l'aide sociale."
                            ],
                            "children": []
                        }
                    ]
                }
            ]
        },
        {
            "label": "2",
            "type": "heading",
            "content": [
                "Art. 63, al. 1bis"
            ],
            "children": [
                {
                    "label": "",
                    "type": "list",
                    "children": [
                        {
                            "label": "1bis.",
                            "type": "list_item",
                            "content": [
                                "Lors de l'examen d'une \u00e9ventuelle r\u00e9vocation selon l'al. 1, let. c, il convient d'examiner si la personne a par sa propre faute provoqu\u00e9 sa d\u00e9pendance \u00e0 l'aide sociale et si elle a insuffisamment exploit\u00e9 son potentiel de travail ou les autres possibilit\u00e9s qu'elle avait de s'affranchir durablement de l'aide sociale."
                            ],
                            "children": []
                        }
                    ]
                }
            ]
        },
        {
            "label": "1",
            "type": "heading",
            "content": [
                "II"
            ],
            "children": [
                {
                    "label": "",
                    "type": "list",
                    "children": [
                        {
                            "label": "1.",
                            "type": "list_item",
                            "content": [
                                "La pr\u00e9sente loi est sujette au r\u00e9f\u00e9rendum."
                            ],
                            "children": []
                        },
                        {
                            "label": "2.",
                            "type": "list_item",
                            "content": [
                                "Le Conseil f\u00e9d\u00e9ral fixe la date de l'entr\u00e9e en vigueur."
                            ],
                            "children": []
                        }
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "The image appears to be a blank white page. There is no visible text, markings, or content of any kind that I can discern or describe. The entire image consists of a uniform white background with no distinguishable features or elements."
                    ]
                }
            ]
        }
    ]
}
