=== Demokratis-ch/demokratis-ml/src/evaluation/json_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "DocNode",
    "type": "object",
    "properties": {
      "label": {
        "type": "string",
        "description": "Label of the node, e.g. '1.2' or '1bis' or 'a)' etc. May be empty."
      },
      "type": {
        "type": "string",
        "enum": ["document", "heading", "content", "list", "list_item", "footnote", "image", "table"],
        "description": "Type of the node."
      },
      "content": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "Array of content strings. Usually only one string, but may be more in case of multiple paragraphs."
      },
      "children": {
        "type": "array",
        "items": {
          "$ref": "#"
        },
        "description": "Array of nested nodes."
      },
      "indent_level": {
        "type": "integer",
        "description": "Indentation level of the node. 0 is the leftmost."
      }
    },
    "required": ["label", "type"],
    "additionalProperties": false
  }

=== Demokratis-ch/demokratis-ml/research/structure-extraction/sample-outputs/zg/consultation_4947_2024-10-31/52984-de-DRAFT-eafdd65f4ef21b14a910d72a9824a656364e147a_json_schema.json
{
    "label": "",
    "type": "document",
    "content": [],
    "children": [
        {
            "label": "",
            "type": "content",
            "content": [
                "Here is the full document content formatted as markdown:"
            ]
        },
        {
            "label": "1",
            "type": "heading",
            "content": [
                "Antrag der Volkswirtschaftsdirektion zum Erlass der Verordnung \u00fcber die Beherbergungsabgabe"
            ],
            "children": []
        },
        {
            "label": "1",
            "type": "heading",
            "content": [
                "Verordnung \u00fcber die Beherbergungsabgabe"
            ],
            "children": [
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Vom [...]"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Von diesem Gesch\u00e4ft tangierte Erlasse (BGS-Nummern)"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Neu:               ???.???"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Ge\u00e4ndert:          \u2013"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Aufgehoben:        \u2013"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "*Der Regierungsrat,*"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "gest\u00fctzt auf \u00a7 4a des Gesetzes \u00fcber die Beherbergungsabgabe[^BGS 944.2]"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "*beschliesst,*"
                    ]
                }
            ]
        },
        {
            "label": "1",
            "type": "heading",
            "content": [
                "I."
            ],
            "children": [
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Der Erlass BGS ???.???, Verordnung \u00fcber die Beherbergungsabgabe, wird als neuer Erlass publiziert."
                    ]
                }
            ]
        },
        {
            "label": "2",
            "type": "heading",
            "content": [
                "\u00a7 1          Abgabenh\u00f6he"
            ],
            "children": [
                {
                    "label": "",
                    "type": "list",
                    "children": [
                        {
                            "label": "1.",
                            "type": "list_item",
                            "content": [
                                "Die Abgabenh\u00f6he betr\u00e4gt 4 Franken."
                            ],
                            "children": []
                        }
                    ]
                }
            ]
        },
        {
            "label": "2",
            "type": "heading",
            "content": [
                "\u00a7 2          Mindestabgabe an die kantonale Tourismusorganisation"
            ],
            "children": [
                {
                    "label": "",
                    "type": "list",
                    "children": [
                        {
                            "label": "1.",
                            "type": "list_item",
                            "content": [
                                "Mindestens Fr. 2.95 pro Logiernacht wird der kantonalen Tourismusorganisation gutgeschrieben. Der Rest der Beherbergungsabgabe kann der lokalen Tourismusorganisation gutgeschrieben werden."
                            ],
                            "children": []
                        }
                    ]
                }
            ]
        },
        {
            "label": "1",
            "type": "heading",
            "content": [
                "II."
            ],
            "children": [
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Keine Fremd\u00e4nderungen."
                    ]
                }
            ]
        },
        {
            "label": "1",
            "type": "heading",
            "content": [
                "III."
            ],
            "children": [
                {
                    "label": "",
                    "type": "list",
                    "children": [
                        {
                            "label": "",
                            "type": "list_item",
                            "content": [
                                "Keine Fremdaufhebungen."
                            ],
                            "children": []
                        }
                    ]
                }
            ]
        },
        {
            "label": "1",
            "type": "heading",
            "content": [
                "IV."
            ],
            "children": [
                {
                    "label": "",
                    "type": "list",
                    "children": [
                        {
                            "label": "",
                            "type": "list_item",
                            "content": [
                                "Diese Verordnung tritt auf den 1. Januar 2026 in Kraft."
                            ],
                            "children": []
                        },
                        {
                            "label": "Ort",
                            "type": "list_item",
                            "content": [
                                ", [Datum]"
                            ],
                            "children": []
                        }
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Der Regierungsrat"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Die Frau Landammann"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Silvia Thalmann-Gut"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Die stv. Landschreiberin"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Ren\u00e9e Spillmann Siegwart"
                    ]
                }
            ]
        }
    ]
}

=== Demokratis-ch/demokratis-ml/research/structure-extraction/sample-outputs/ch/consultation_4956_2024-11-21/53135-de-DRAFT-66e5133012b9947ac386cdc561dec2a9fb7b8037_json_schema.json
{
    "label": "",
    "type": "document",
    "content": [],
    "children": [
        {
            "label": "1",
            "type": "heading",
            "content": [
                "Bundesgesetz                                                                Vorentwurf"
            ],
            "children": [
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "\u00fcber die Ausl\u00e4nderinnen und Ausl\u00e4nder und \u00fcber die Inte-"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "gration"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "(Ausl\u00e4nder- und Integrationsgesetz)"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "(Kein Verlust des Aufenthaltsrechts bei unverschuldeter Sozialhilfe-"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "abh\u00e4ngigkeit)"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "\u00c4nderung vom ..."
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Die Bundesversammlung der Schweizerischen Eidgenossenschaft,"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "nach Einsicht in den Bericht der [Name der Kommission des National- oder"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "St\u00e4nderates] vom [Datum des Entscheids der Kommission][^1]"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "und in die Stellungnahme des Bundesrates vom [Datum][^2],"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "beschliesst:"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "I"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Das Bundesgesetz vom 16. Dezember 2005 \u00fcber die Ausl\u00e4nderinnen und Ausl\u00e4nder[^3]"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "und \u00fcber die Integration wird wie folgt ge\u00e4ndert:"
                    ]
                }
            ]
        },
        {
            "label": "2",
            "type": "heading",
            "content": [
                "Art. 62 Abs. 1bis"
            ],
            "children": [
                {
                    "label": "",
                    "type": "list",
                    "children": [
                        {
                            "label": "1bis.",
                            "type": "list_item",
                            "content": [
                                "Bei der Pr\u00fcfung eines allf\u00e4lligen Widerrufs nach Absatz 1 Buchstabe e ist zu"
                            ],
                            "children": []
                        }
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "ber\u00fccksichtigen, ob die betroffene Person durch eigenes Verschulden die Sozialhil-"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "feabh\u00e4ngigkeit herbeigef\u00fchrt und ihr Arbeitspotenzial oder andere M\u00f6glichkeiten,"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "nachhaltig von der Sozialhilfe unabh\u00e4ngig zu werden, unzureichend genutzt hat."
                    ]
                }
            ]
        },
        {
            "label": "2",
            "type": "heading",
            "content": [
                "Art. 63 Abs. 1bis"
            ],
            "children": [
                {
                    "label": "",
                    "type": "list",
                    "children": [
                        {
                            "label": "1bis.",
                            "type": "list_item",
                            "content": [
                                "Bei der Pr\u00fcfung eines allf\u00e4lligen Widerrufs nach Absatz 1 Buchstabe c ist zu"
                            ],
                            "children": []
                        }
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "ber\u00fccksichtigen, ob die betroffene Person durch eigenes Verschulden die Sozialhil-"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "feabh\u00e4ngigkeit herbeigef\u00fchrt und ihr Arbeitspotenzial oder andere M\u00f6glichkeiten,"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "nachhaltig von der Sozialhilfe unabh\u00e4ngig zu werden, unzureichend genutzt hat."
                    ]
                }
            ]
        },
        {
            "label": "1",
            "type": "heading",
            "content": [
                "II"
            ],
            "children": [
                {
                    "label": "",
                    "type": "list",
                    "children": [
                        {
                            "label": "1.",
                            "type": "list_item",
                            "content": [
                                "Dieses Gesetz untersteht dem fakultativen Referendum."
                            ],
                            "children": []
                        },
                        {
                            "label": "2.",
                            "type": "list_item",
                            "content": [
                                "Der Bundesrat bestimmt das Inkrafttreten."
                            ],
                            "children": []
                        }
                    ]
                }
            ]
        }
    ]
}

=== Demokratis-ch/demokratis-ml/research/structure-extraction/sample-outputs/ag/consultation_4954_2024-11-15/53121-de-VARIOUS_TEXT-a4fe3d0724010b1ab5829b205c4c4a701e4b5f56_json_schema.json
{
    "label": "",
    "type": "document",
    "content": [],
    "children": [
        {
            "label": "1",
            "type": "heading",
            "content": [
                "Synopse Beilage zum Anh\u00f6rungsbericht"
            ],
            "children": []
        },
        {
            "label": "1",
            "type": "heading",
            "content": [
                "Steuerrabatt bei \u00dcbersch\u00fcssen und guter Finanzlage; Steuergesetz (StG); \u00c4nderung"
            ],
            "children": [
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Von diesem Gesch\u00e4ft tangierte Erlasse (SAR Nummern)"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Neu:             \u2013"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Ge\u00e4ndert:        651.100"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Aufgehoben: \u2013"
                    ]
                }
            ]
        },
        {
            "label": "",
            "type": "table",
            "content": [
                "| Geltendes Recht | Entwurf des Regierungsrats vom 14.10.2024 | Abweichende Antr\u00e4ge der Kommission X vom ... | Stellungnahme des Regierungsrats | Ergebnis der 1. Beratung vom ... |",
                "|-----------------|-------------------------------------------|----------------------------------------------|----------------------------------|----------------------------------|",
                "| | Steuergesetz (StG) | | | |",
                "| | Der Grosse Rat des Kantons Aargau | | | |",
                "| | beschliesst: | | | |",
                "| | I. | | | |",
                "| | Der Erlass SAR 651.100 (Steuergesetz [StG] vom 15. Dezember 1998) (Stand 1. Juli 2024) wird wie folgt ge\u00e4ndert: | | | |",
                "| | \u00a7 2a IIa. Steuerrabatt | | | |",
                "| | [1.] Der Grosse Rat kann mit der Genehmigung des Jahresberichts mit Jahresrechnung bei guter Finanzlage aus einem Ertrags\u00fcberschuss der Finanzierungsrechnung einen Steuerrabatt in ganzen Steuerfussprozentpunkten auf die ordentliche Kantonssteuer des \u00fcbern\u00e4chsten Jahres gew\u00e4hren. | | | |"
            ],
            "children": []
        },
        {
            "label": "2",
            "type": "heading",
            "content": [
                "Entwurf des Regierungsrats vom 14.10.2024"
            ],
            "children": [
                {
                    "label": "",
                    "type": "list",
                    "children": [
                        {
                            "label": "2.",
                            "type": "list_item",
                            "content": [
                                "Aus dem Ertrags\u00fcberschuss, der f\u00fcr den Steuerrabatt verwendet werden soll, wird eine Steuerrabatt-Reserve ge\u00e4ufnet. Sie ist mit der Bildung der R\u00fcckstellung f\u00fcr den Steuerrabatt im Folgejahr vollst\u00e4ndig aufzul\u00f6sen."
                            ],
                            "children": []
                        },
                        {
                            "label": "3.",
                            "type": "list_item",
                            "content": [
                                "F\u00fcr eine gute Finanzlage gem\u00e4ss Absatz 1 m\u00fcssen unter Ber\u00fccksichtigung des gew\u00e4hrten Steuerrabatts folgende Voraussetzungen erf\u00fcllt sein:"
                            ],
                            "children": [
                                {
                                    "label": "",
                                    "type": "list",
                                    "children": [
                                        {
                                            "label": "a)",
                                            "type": "list_item",
                                            "content": [
                                                "keine Nettoverschuldung (Nettoschuld I),"
                                            ],
                                            "children": []
                                        },
                                        {
                                            "label": "b)",
                                            "type": "list_item",
                                            "content": [
                                                "keine offenen Fehlbetr\u00e4ge der Finanzierungsrechnung,"
                                            ],
                                            "children": []
                                        },
                                        {
                                            "label": "c)",
                                            "type": "list_item",
                                            "content": [
                                                "angemessener Bestand der Ausgleichsreserve gem\u00e4ss Absatz 4."
                                            ],
                                            "children": []
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "label": "4.",
                            "type": "list_item",
                            "content": [
                                "Der Bestand der Ausgleichsreserve gilt als angemessen, wenn er mindestens 3 % des Gesamtertrags der Finanzierungsrechnung des jeweils aktuellen Aufgaben- und Finanzplans erreicht."
                            ],
                            "children": []
                        }
                    ]
                }
            ]
        },
        {
            "label": "2",
            "type": "heading",
            "content": [
                "II."
            ],
            "children": [
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Keine Fremd\u00e4nderungen."
                    ]
                }
            ]
        },
        {
            "label": "1",
            "type": "heading",
            "content": [
                "Entwurf des Regierungsrats vom 14.10.2024"
            ],
            "children": []
        },
        {
            "label": "3",
            "type": "heading",
            "content": [
                "III."
            ],
            "children": [
                {
                    "label": "",
                    "type": "list",
                    "children": [
                        {
                            "label": "",
                            "type": "list_item",
                            "content": [
                                "Keine Fremdaufhebungen."
                            ],
                            "children": []
                        }
                    ]
                }
            ]
        },
        {
            "label": "3",
            "type": "heading",
            "content": [
                "IV."
            ],
            "children": [
                {
                    "label": "",
                    "type": "list",
                    "children": [
                        {
                            "label": "",
                            "type": "list_item",
                            "content": [
                                "Die \u00c4nderung unter Ziff. I. tritt am 1. Januar 2026 in Kraft. Sie untersteht nach den Voraussetzungen der Kantonsverfassung der nachtr\u00e4glichen Volksabstimmung."
                            ],
                            "children": []
                        }
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Aarau,"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Pr\u00e4sident des Grossen Rats"
                    ]
                },
                {
                    "label": "",
                    "type": "content",
                    "content": [
                        "Protokollf\u00fchrerin"
                    ]
                }
            ]
        }
    ]
}
